language: python
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
services:
  - "postgresql"
install:
  - "pip install -e ."
  - "pip install -r requirements-dev.txt"
  - "pip install coveralls pytest-cov"
script:
  - "flake8 --exclude=migrations ."
  - "py.test --ds=seed_auth_api.testsettings --cov=authapi */tests.py"
after_success:
  - "coveralls"
