language: python
python:
  - "2.7"
  - "3.4"
services:
  - "postgresql"
install:
  - "pip install -e ."
  - "pip install -r requirements-dev.txt"
script:
  - "flake8 ."
  - "py.test --ds=seed_auth_api.testsettings */tests.py"
